### ISSUE TITLE
Extension Functions aren't available at runtime

### ISSUE THREAD

**Issue by PriestVallon** [moneymanagerex/SQLite-Android-Bindings#2]
I've gotten this working with the NDK but I need to add extra functions to SQLite. So the Android.mk is calling the sqlite3secure.c file and that is calling the extensionfunctions.c but when I try to use any of the new functions in that file like "cos" I get the error "no such function: cos"

**Comment by guanlisheng** [comment]
@PriestVallon  Sorry for the late and you may need to add some MACRO to enable such extension.
`DSQLITE_ENABLE_EXTFUNC`

**Comment by guanlisheng** [comment]
@PriestVallon will close the issue if there is no additional feedback
